---
title: "04_RandomForest"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up

### Load libraries
```{r}
library(mctoolsr)
library(plyr) # always load before tidyverse to avoid conflicts with dplyr
library(tidyverse) # lazily load all of tidyverse, just in case I want to use it.
library(vegan)
library(plotly)
library(readr)
#library(rowr)
library(caret)
library(ranger)
library(stringr)
library(Boruta)

set.seed(10)
```

### Set up input and output directories
```{r Set up input and output directories, include = FALSE}
project.fp <- "/Users/coin8046/Desktop/FiererLabNotebook/mustard_microbiome/mustard_ITS/R.analyses"
clean_data.fp <- file.path(project.fp, "01_clean_data")
    outputs_01_clean.fp <- file.path(clean_data.fp, "outputs")

explr_02.fp <- file.path(project.fp, "02_exploration")
    outputs_02.fp <- file.path(explr_02.fp, "outputs")

randfor_04.fp <- file.path(project.fp, "04_RandomForest")
  outputs_04.fp <- file.path(randfor_04.fp, "outputs")
  figures_04.fp <- file.path(randfor_04.fp, "figures")

if (!dir.exists(randfor_04.fp)) {dir.create(randfor_04.fp, recursive = TRUE)}    
if (!dir.exists(outputs_04.fp)) {dir.create(outputs_04.fp, recursive = TRUE)}
if (!dir.exists(figures_04.fp)) {dir.create(figures_04.fp, recursive = TRUE)}
```

## Data set up 

### Read in ITS data
```{r}
# rhizosphere data
## rarefied, filtered data: chem samples only

input_rhizo.chem <- readRDS(paste0(outputs_02.fp, "/input_rhizo.chem.RDS"))
input_rhzC.M <- readRDS(paste0(outputs_02.fp, "/input_rhzC.M.RDS"))
input_rhzC.S <- readRDS(paste0(outputs_02.fp, "/input_rhzC.S.RDS"))

input_root.chem <- readRDS(paste0(outputs_02.fp, "/input_root.chem.RDS"))
input_rtC.M <- readRDS(paste0(outputs_02.fp, "/input_rtM.com.RDS"))
input_rtC.S <- readRDS(paste0(outputs_02.fp, "/input_rtS.com.RDS"))
```

### Read in sample metadata
```{r}
metadata.r <- readRDS("/Users/coin8046/Desktop/FiererLabNotebook/mustard_microbiome/mustard_chem/01_outputs/plant.chem_data.RDS")

metadata <- metadata.r[-c(70), ]
sampleIDs <- metadata$Pot.ID

```

## Prep dataframes for RF
```{r}
#input_rhzC.M

ASV_rhizo.M <- summarize_taxonomy(input_rhzC.M, level = 7, report_higher_tax =  FALSE) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "sample_id") %>% 
  inner_join(input_rhzC.M$map_loaded, by = "sample_id")

#"Allyl..µmol.g."
ASV_rhizo.M.rf <- ASV_rhizo.M %>% 
  column_to_rownames(var = "sample_id") %>% 
  dplyr::select(c("ASV_145","ASV_16","ASV_2","ASV_25","ASV_4","ASV_44","Allyl..µmol.g."))
  # dplyr::select(-c("Primer_Plate", "Primer_Well", "sample_type_1", "sample_type_2", "ReadCount.raw", "condition","soil_type.x","sterility.x", "SampleID_3", "flower.buds.appear", "full.flower.appear", "seed.pods.appear", "no.flowers..pods.drying", "Spider.mites", "total.seed.count", "Last.Seeds.Collected", "Root.Rhizo.Harvest","total_seed_mass","sample.name","height_9","height_15","Updated.Mass..g.","X3.Butenyl..µmol.g.","X3MT..µmol.g.","Indoles..µmol.g.","treatment","soil_type.y","sterility.y"))
```


## Boruta feature selection
```{r}
#https://academic.oup.com/bib/article/20/2/492/4554516
#https://www.machinelearningplus.com/machine-learning/feature-selection/

# Perform Boruta search
boruta_output.rz.M <- Boruta(Allyl..µmol.g. ~., 
                        data=na.omit(ASV_rhizo.M.rf), doTrace=0) 

boruta_output.rz.M
boruta_signif.rz.M <- getSelectedAttributes(boruta_output.rz.M, withTentative = TRUE)
```

## Random forest training

```{r}
### Separate training and testing data
set.seed(100) #100
random_ordered <- ASV_rhizo.M.rf[sample(nrow(ASV_rhizo.M.rf)),]
number_training_samples <- ceiling(nrow(random_ordered) * 0.6)
train <- random_ordered[1:number_training_samples,]
test <- random_ordered[(number_training_samples + 1):nrow(random_ordered),]

### Create random forest models
ranger1rzM1 <- ranger(Allyl..µmol.g. ~.,
                  data=train,
                  num.trees = 1000,
                  splitrule = "variance",
                  write.forest = TRUE, 
                  #min.node.size = 5, 
                  classification = FALSE, 
                  seed = 10)
print(ranger1rzM1)



### another way to create RF model
control <- trainControl(method='repeatedcv', 
                        number=10, 
                        repeats=3)
mtry <- sqrt(ncol(train))
tunegrid <- expand.grid(.mtry=mtry)

train1 <- train(Allyl..µmol.g. ~.,
                data=train,
                method="rf")
                #tuneGrid=tunegrid)
                #trControl=control)
print(train1)
varImp(train1)
```

## test predictions
```{r}
pred <- predict(ranger1rzM1, data = test)

pred.1 <- pred$predictions %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "test_num")

cor.test(pred$predictions, test$Allyl..µmol.g.)

pred2 <- predict(train1, newdata = test) %>% as.data.frame() %>% rownames_to_column(var = "sample_num")
cor.test(pred2$., test$Allyl..µmol.g.)


check1 <- test %>% 
  rownames_to_column(var = "sample_num") %>% 
  rownames_to_column(var = "test_num") %>% 
  select(c("Allyl..µmol.g.", "sample_num", "test_num")) %>% 
  inner_join(pred.1, by= "test_num") %>% 
  inner_join(pred2, by = "sample_num")

cor.test(check1$..x, check1$Allyl..µmol.g.)
cor.test(check1$..y, check1$Allyl..µmol.g.)


predcor <- ggplot(check1, aes(x=..x, y=Allyl..µmol.g.))+ #Allyl..µmol.g.
  geom_point()+
  geom_smooth(method = "lm")+
  #geom_abline(slope = 1, intercept = 0, color = 'red')+
  ylab("true proportion of Allyl in seeds")+
  xlab("predicted proportion Allyl in seeds")+
  #labs(title = "Predicted by slurry bacterial family composition")+
  theme_bw(base_size = 18)+
  ggtitle("Predictive accuracy of Random Forest model")

predcor
```
